# Site settings
title: Refresh Hilo
email: your-email@domain.com
description: "Refresh Hilo is a collective of web professionals, developers and designers, working together to foster new ideas and refresh the creative, technical and professional aspects of their trade. All are welcome to contribute or learn."
baseurl: ""
url: "http://www.refresh-hilo.org"
timezone: Pacific/Honolulu

# Site assets & libraries
jquery: 1.11.1
modernizr: 2.6.2
bootstrap: 3.2.0

# Collections
collections:
  events:
    output: true
    permalink: /event/:path/
  members:
    output: true
    permalink: /members/:path/

# Build settings
markdown: kramdown
permalink: pretty

# Misc site vars
facebook: https://www.facebook.com/groups/refresh.hilo/
meetup: http://www.meetup.com/Refresh-Hilo
googleplus: https://plus.google.com/communities/107501944160515171773
twitter: https://twitter.com/refreshhilo
github: https://github.com/Refresh-Hilo

# API Keys
key_gmap: AIzaSyAQ1PDqxaPmEjnVir_77TmLsEC1IYB11Ew