# Site settings
title: Refresh Hilo
email: your-email@domain.com
description: "Refresh Hilo is a collective of web professionals, developers and designers, working together to foster new ideas and refresh the creative, technical and professional aspects of their trade. All are welcome to contribute or learn."
baseurl: ""
url: "http://www.refresh-hilo.org"
timezone: Pacific/Honolulu

# Site assets & libraries
jquery: 1.11.1
modernizr: 2.6.2
bootstrap: 3.2.0

# Collections
collections:
  events:
    output: true
    permalink: /event/:path/
  members:
    output: true
    permalink: /members/:path/

# Build settings
markdown: kramdown
permalink: pretty

# Misc site vars
facebook: undefined
meetup: http://www.meetup.com/Refresh-Hilo
google+: https://plus.google.com/100423298758135837509
twitter: undefined